api_platform:
    title: Osira API
    description: Self-hosted monitoring control plane API.
    version: 0.1.0
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: false
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    patch_formats:
        json: ['application/merge-patch+json', 'application/json']
    docs_formats:
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    mapping:
        paths:
            - '%kernel.project_dir%/src/User/Presentation/Api/Resource'
            - '%kernel.project_dir%/src/Rbac/Presentation/Api/Resource'
            - '%kernel.project_dir%/src/Node/Presentation/Api/Resource'
            - '%kernel.project_dir%/src/NodeGroup/Presentation/Api/Resource'
            - '%kernel.project_dir%/src/Enrollment/Presentation/Api/Resource'
            - '%kernel.project_dir%/src/Audit/Presentation/Api/Resource'
    defaults:
        stateless: true
        pagination_client_enabled: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        persist_authorization: true
        http_auth:
            JWT:
                scheme: bearer
                bearerFormat: JWT
        swagger_ui_extra_configuration:
            docExpansion: list
            displayRequestDuration: true
            filter: true
