dh_auditor:
    enabled: true
    timezone: UTC
    user_provider: App\Audit\Infrastructure\AuditUserProvider
    providers:
        doctrine:
            table_prefix: audit_
            table_suffix: ''
            ignored_columns:
                - createdAt
                - updatedAt
            entities:
                App\User\Domain\Entity\User:
                    ignored_columns:
                        - password
                        - technicalRoles
                App\Rbac\Domain\Entity\Role: ~
                App\Rbac\Domain\Entity\Permission: ~
                App\Node\Domain\Entity\Node: ~
                App\NodeGroup\Domain\Entity\NodeGroup: ~
                App\Agent\Domain\Entity\Agent: ~
                App\Enrollment\Domain\Entity\EnrollmentToken:
                    ignored_columns:
                        - tokenHash
            storage_services:
                - '@doctrine.orm.default_entity_manager'
            auditing_services:
                - '@doctrine.orm.default_entity_manager'
            viewer: false
