dh_auditor:
    enabled: true
    timezone: UTC
    user_provider: App\Audit\AuditUserProvider
    providers:
        doctrine:
            table_prefix: audit_
            table_suffix: ''
            ignored_columns:
                - createdAt
                - updatedAt
            entities:
                App\Entity\User:
                    ignored_columns:
                        - password
                        - technicalRoles
                App\Entity\Role: ~
                App\Entity\Permission: ~
                App\Entity\Node: ~
                App\Entity\NodeGroup: ~
                App\Entity\Agent: ~
                App\Entity\EnrollmentToken:
                    ignored_columns:
                        - tokenHash
            storage_services:
                - '@doctrine.orm.default_entity_manager'
            auditing_services:
                - '@doctrine.orm.default_entity_manager'
            viewer: false
