<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260825160000 extends AbstractMigration
{
    private const string ACKNOWLEDGE_PERMISSION_ID = '00000000-0000-0000-0000-000000000034';
    private const string COMMENT_PERMISSION_ID = '00000000-0000-0000-0000-000000000035';

    public function getDescription(): string
    {
        return 'Add incident acknowledgements, comments, timeline activities, audit, and RBAC.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql('ALTER TABLE incidents ADD acknowledged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE incidents ADD acknowledged_by_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE incidents ADD CONSTRAINT FK_31F2B7C7C7738F27 FOREIGN KEY (acknowledged_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_E65135D04DEFF5F ON incidents (acknowledged_by_id)');

        $this->addSql('CREATE TABLE incident_activities (id UUID NOT NULL, incident_id UUID NOT NULL, actor_id UUID NOT NULL, actor_ulid VARCHAR(26) NOT NULL, actor_email VARCHAR(180) NOT NULL, type VARCHAR(24) NOT NULL, message TEXT DEFAULT NULL, acknowledgement_key VARCHAR(26) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE incident_activities ADD CONSTRAINT FK_2448600A3A8B2A3F FOREIGN KEY (incident_id) REFERENCES incidents (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_activities ADD CONSTRAINT FK_2448600A10DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_FB3CD85459E53FB9 ON incident_activities (incident_id)');
        $this->addSql('CREATE INDEX IDX_FB3CD85410DAF24A ON incident_activities (actor_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_incident_acknowledgement ON incident_activities (acknowledgement_key)');
        $this->addSql('CREATE INDEX idx_incident_activities_timeline ON incident_activities (incident_id, created_at, id)');
        $this->createAuditTable('audit_incident_activities');

        $this->addPermission(self::ACKNOWLEDGE_PERMISSION_ID, 'incidents.acknowledge', 'Acknowledge incidents', 'Acknowledge firing incidents without changing their lifecycle status.');
        $this->addPermission(self::COMMENT_PERMISSION_ID, 'incidents.comment', 'Comment on incidents', 'Add immutable comments to incidents.');
        foreach ([self::ACKNOWLEDGE_PERMISSION_ID, self::COMMENT_PERMISSION_ID] as $permissionId) {
            foreach (['00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000102', '00000000-0000-0000-0000-000000000103'] as $roleId) {
                $this->addSql(\sprintf("INSERT INTO role_permissions (role_id, permission_id) VALUES ('%s', '%s')", $roleId, $permissionId));
            }
        }
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        foreach ([self::ACKNOWLEDGE_PERMISSION_ID, self::COMMENT_PERMISSION_ID] as $permissionId) {
            $this->addSql("DELETE FROM role_permissions WHERE permission_id = '".$permissionId."'");
            $this->addSql("DELETE FROM permissions WHERE id = '".$permissionId."'");
        }
        $this->addSql('DROP TABLE audit_incident_activities');
        $this->addSql('DROP TABLE incident_activities');
        $this->addSql('ALTER TABLE incidents DROP CONSTRAINT FK_31F2B7C7C7738F27');
        $this->addSql('DROP INDEX IDX_E65135D04DEFF5F');
        $this->addSql('ALTER TABLE incidents DROP acknowledged_at');
        $this->addSql('ALTER TABLE incidents DROP acknowledged_by_id');
    }

    private function addPermission(string $id, string $code, string $name, string $description): void
    {
        $this->addSql(\sprintf("INSERT INTO permissions (id, code, name, description, category, created_at, updated_at) VALUES ('%s', '%s', '%s', '%s', 'Monitoring', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)", $id, $code, $name, $description));
    }

    private function createAuditTable(string $table): void
    {
        $this->addSql(\sprintf('CREATE TABLE %s (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSONB DEFAULT NULL, extra_data JSONB DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))', $table));
        $hash = md5($table);
        foreach (['type', 'object_id', 'discriminator', 'transaction_hash', 'blame_id', 'created_at'] as $column) {
            $this->addSql(\sprintf('CREATE INDEX %s_%s_idx ON %s (%s)', $column, $hash, $table, $column));
        }
    }
}
