<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260826150000 extends AbstractMigration
{
    /** @var array<string, string> */
    private const array PERMISSIONS = [
        '00000000-0000-0000-0000-000000000048' => 'alert_rules.read|Read alert rules|View alert rules and their template, node group, and node assignments.',
        '00000000-0000-0000-0000-000000000049' => 'alert_rules.create|Create alert rules|Create alert rules and assign them to templates, node groups, or nodes.',
        '00000000-0000-0000-0000-000000000050' => 'alert_rules.update|Update alert rules|Update alert rules and their assignments.',
        '00000000-0000-0000-0000-000000000051' => 'alert_rules.delete|Delete alert rules|Delete alert rules.',
    ];

    public function getDescription(): string
    {
        return 'Expose AlertRule CRUD: add description/updated_at, rename threshold to expected_value, add audit table and RBAC permissions.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql('ALTER TABLE alert_rules ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE alert_rules ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('UPDATE alert_rules SET updated_at = created_at WHERE updated_at IS NULL');
        $this->addSql('ALTER TABLE alert_rules ALTER updated_at SET NOT NULL');
        $this->addSql('ALTER TABLE alert_rules RENAME COLUMN threshold TO expected_value');

        $this->createAuditTable('audit_alert_rules');

        foreach (self::PERMISSIONS as $id => $definition) {
            [$code, $name, $description] = explode('|', $definition, 3);
            $this->addSql(\sprintf("INSERT INTO permissions (id, code, name, description, category, created_at, updated_at) VALUES ('%s', '%s', '%s', '%s', 'Monitoring', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)", $id, $code, $name, $description));
            foreach (['00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000102'] as $roleId) {
                $this->addSql(\sprintf("INSERT INTO role_permissions (role_id, permission_id) VALUES ('%s', '%s')", $roleId, $id));
            }
        }
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id) VALUES ('00000000-0000-0000-0000-000000000104', '00000000-0000-0000-0000-000000000048')");
        foreach (['00000000-0000-0000-0000-000000000048', '00000000-0000-0000-0000-000000000049', '00000000-0000-0000-0000-000000000050'] as $permissionId) {
            $this->addSql(\sprintf("INSERT INTO role_permissions (role_id, permission_id) VALUES ('00000000-0000-0000-0000-000000000103', '%s')", $permissionId));
        }
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        foreach (array_keys(self::PERMISSIONS) as $id) {
            $this->addSql("DELETE FROM role_permissions WHERE permission_id = '".$id."'");
            $this->addSql("DELETE FROM permissions WHERE id = '".$id."'");
        }
        $this->addSql('DROP TABLE audit_alert_rules');
        $this->addSql('ALTER TABLE alert_rules RENAME COLUMN expected_value TO threshold');
        $this->addSql('ALTER TABLE alert_rules DROP updated_at');
        $this->addSql('ALTER TABLE alert_rules DROP description');
    }

    private function createAuditTable(string $table): void
    {
        $this->addSql(\sprintf('CREATE TABLE %s (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSONB DEFAULT NULL, extra_data JSONB DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))', $table));
        $hash = md5($table);
        foreach (['type', 'object_id', 'discriminator', 'transaction_hash', 'blame_id', 'created_at'] as $column) {
            $this->addSql(\sprintf('CREATE INDEX %s_%s_idx ON %s (%s)', $column, $hash, $table, $column));
        }
    }
}
