<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260825073710 extends AbstractMigration
{
    private const string INCIDENTS_READ_PERMISSION_ID = '00000000-0000-0000-0000-000000000028';

    public function getDescription(): string
    {
        return 'Add effective alert rules, incident lifecycle state, incident audit, and incidents.read RBAC.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql('CREATE TABLE alert_rules (id UUID NOT NULL, name VARCHAR(128) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, operator VARCHAR(8) NOT NULL, threshold VARCHAR(255) NOT NULL, recovery_threshold VARCHAR(255) DEFAULT NULL, evaluation_window_seconds INT NOT NULL, required_occurrences INT NOT NULL, severity VARCHAR(16) NOT NULL, is_enabled BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, item_definition_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_63C06ED73DB201CA ON alert_rules (item_definition_id)');
        $this->addSql('ALTER TABLE alert_rules ADD CONSTRAINT chk_alert_rules_window_positive CHECK (evaluation_window_seconds > 0)');
        $this->addSql('ALTER TABLE alert_rules ADD CONSTRAINT chk_alert_rules_occurrences_positive CHECK (required_occurrences > 0)');
        $this->addSql('CREATE TABLE alert_rule_monitoring_templates (alert_rule_id UUID NOT NULL, monitoring_template_id UUID NOT NULL, PRIMARY KEY (alert_rule_id, monitoring_template_id))');
        $this->addSql('CREATE INDEX IDX_8032ED6BEA1DA493 ON alert_rule_monitoring_templates (alert_rule_id)');
        $this->addSql('CREATE INDEX IDX_8032ED6BBB64145D ON alert_rule_monitoring_templates (monitoring_template_id)');
        $this->addSql('CREATE TABLE alert_rule_node_groups (alert_rule_id UUID NOT NULL, node_group_id UUID NOT NULL, PRIMARY KEY (alert_rule_id, node_group_id))');
        $this->addSql('CREATE INDEX IDX_56ADD747EA1DA493 ON alert_rule_node_groups (alert_rule_id)');
        $this->addSql('CREATE INDEX IDX_56ADD74740F9C112 ON alert_rule_node_groups (node_group_id)');
        $this->addSql('CREATE TABLE alert_rule_nodes (alert_rule_id UUID NOT NULL, node_id UUID NOT NULL, PRIMARY KEY (alert_rule_id, node_id))');
        $this->addSql('CREATE INDEX IDX_52004DECEA1DA493 ON alert_rule_nodes (alert_rule_id)');
        $this->addSql('CREATE INDEX IDX_52004DEC460D9FD7 ON alert_rule_nodes (node_id)');
        $this->addSql('CREATE TABLE incidents (id UUID NOT NULL, severity VARCHAR(16) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, labels JSON NOT NULL, active_identity VARCHAR(64) DEFAULT NULL, last_value VARCHAR(255) NOT NULL, first_triggered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_triggered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(16) NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, occurrences INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, node_id UUID NOT NULL, alert_rule_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E65135D0460D9FD7 ON incidents (node_id)');
        $this->addSql('CREATE INDEX IDX_E65135D0EA1DA493 ON incidents (alert_rule_id)');
        $this->addSql('CREATE INDEX idx_incidents_status ON incidents (status)');
        $this->addSql('CREATE INDEX idx_incidents_severity ON incidents (severity)');
        $this->addSql('CREATE INDEX idx_incidents_first_triggered_at ON incidents (first_triggered_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_incidents_active_identity ON incidents (active_identity)');
        $this->addSql('CREATE TABLE audit_incidents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSONB DEFAULT NULL, extra_data JSONB DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_8dfec2a874d18e400ba5a3948da6b05b_idx ON audit_incidents (type)');
        $this->addSql('CREATE INDEX object_id_8dfec2a874d18e400ba5a3948da6b05b_idx ON audit_incidents (object_id)');
        $this->addSql('CREATE INDEX discriminator_8dfec2a874d18e400ba5a3948da6b05b_idx ON audit_incidents (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_8dfec2a874d18e400ba5a3948da6b05b_idx ON audit_incidents (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_8dfec2a874d18e400ba5a3948da6b05b_idx ON audit_incidents (blame_id)');
        $this->addSql('CREATE INDEX created_at_8dfec2a874d18e400ba5a3948da6b05b_idx ON audit_incidents (created_at)');
        $this->addSql('ALTER TABLE alert_rules ADD CONSTRAINT FK_63C06ED73DB201CA FOREIGN KEY (item_definition_id) REFERENCES item_definitions (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE alert_rule_monitoring_templates ADD CONSTRAINT FK_8032ED6BEA1DA493 FOREIGN KEY (alert_rule_id) REFERENCES alert_rules (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alert_rule_monitoring_templates ADD CONSTRAINT FK_8032ED6BBB64145D FOREIGN KEY (monitoring_template_id) REFERENCES monitoring_templates (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alert_rule_node_groups ADD CONSTRAINT FK_56ADD747EA1DA493 FOREIGN KEY (alert_rule_id) REFERENCES alert_rules (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alert_rule_node_groups ADD CONSTRAINT FK_56ADD74740F9C112 FOREIGN KEY (node_group_id) REFERENCES node_groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alert_rule_nodes ADD CONSTRAINT FK_52004DECEA1DA493 FOREIGN KEY (alert_rule_id) REFERENCES alert_rules (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alert_rule_nodes ADD CONSTRAINT FK_52004DEC460D9FD7 FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incidents ADD CONSTRAINT FK_E65135D0460D9FD7 FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incidents ADD CONSTRAINT FK_E65135D0EA1DA493 FOREIGN KEY (alert_rule_id) REFERENCES alert_rules (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("INSERT INTO permissions (id, code, name, description, category, created_at, updated_at) VALUES ('".self::INCIDENTS_READ_PERMISSION_ID."', 'incidents.read', 'Read incidents', 'View incidents produced by server-side alert evaluation.', 'Monitoring', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        foreach (['101', '102', '103', '104'] as $roleSuffix) {
            $this->addSql("INSERT INTO role_permissions (role_id, permission_id) VALUES ('00000000-0000-0000-0000-000000000".$roleSuffix."', '".self::INCIDENTS_READ_PERMISSION_ID."')");
        }
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql("DELETE FROM role_permissions WHERE permission_id = '".self::INCIDENTS_READ_PERMISSION_ID."'");
        $this->addSql("DELETE FROM permissions WHERE id = '".self::INCIDENTS_READ_PERMISSION_ID."'");
        $this->addSql('ALTER TABLE alert_rules DROP CONSTRAINT FK_63C06ED73DB201CA');
        $this->addSql('ALTER TABLE alert_rule_monitoring_templates DROP CONSTRAINT FK_8032ED6BEA1DA493');
        $this->addSql('ALTER TABLE alert_rule_monitoring_templates DROP CONSTRAINT FK_8032ED6BBB64145D');
        $this->addSql('ALTER TABLE alert_rule_node_groups DROP CONSTRAINT FK_56ADD747EA1DA493');
        $this->addSql('ALTER TABLE alert_rule_node_groups DROP CONSTRAINT FK_56ADD74740F9C112');
        $this->addSql('ALTER TABLE alert_rule_nodes DROP CONSTRAINT FK_52004DECEA1DA493');
        $this->addSql('ALTER TABLE alert_rule_nodes DROP CONSTRAINT FK_52004DEC460D9FD7');
        $this->addSql('ALTER TABLE incidents DROP CONSTRAINT FK_E65135D0460D9FD7');
        $this->addSql('ALTER TABLE incidents DROP CONSTRAINT FK_E65135D0EA1DA493');
        $this->addSql('DROP TABLE alert_rules');
        $this->addSql('DROP TABLE alert_rule_monitoring_templates');
        $this->addSql('DROP TABLE alert_rule_node_groups');
        $this->addSql('DROP TABLE alert_rule_nodes');
        $this->addSql('DROP TABLE incidents');
        $this->addSql('DROP TABLE audit_incidents');
    }
}
