<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260820100000 extends AbstractMigration
{
    private const string PERMISSION_ID = '00000000-0000-0000-0000-000000000027';

    public function getDescription(): string
    {
        return 'Audit agent credential lifecycle, enforce unique credential hashes, and grant agent_credentials.revoke to Super Admin and Admin.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->createAuditTable('audit_agent_credentials');
        $this->addSql('CREATE UNIQUE INDEX uniq_agent_credentials_secret_hash ON agent_credentials (secret_hash)');
        $this->addSql("INSERT INTO permissions (id, code, name, description, category, created_at, updated_at) VALUES ('".self::PERMISSION_ID."', 'agent_credentials.revoke', 'Revoke agent credentials', 'Revoke active control-plane agent credentials.', 'Enrollment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id) VALUES ('00000000-0000-0000-0000-000000000101', '".self::PERMISSION_ID."')");
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id) VALUES ('00000000-0000-0000-0000-000000000102', '".self::PERMISSION_ID."')");
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql("DELETE FROM role_permissions WHERE permission_id = '".self::PERMISSION_ID."'");
        $this->addSql("DELETE FROM permissions WHERE id = '".self::PERMISSION_ID."'");
        $this->addSql('DROP INDEX uniq_agent_credentials_secret_hash');
        $this->addSql('DROP TABLE audit_agent_credentials');
    }

    private function createAuditTable(string $table): void
    {
        $this->addSql(\sprintf('CREATE TABLE %s (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSONB DEFAULT NULL, extra_data JSONB DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))', $table));

        $hash = md5($table);
        foreach (['type', 'object_id', 'discriminator', 'transaction_hash', 'blame_id', 'created_at'] as $column) {
            $this->addSql(\sprintf('CREATE INDEX %s_%s_idx ON %s (%s)', $column, $hash, $table, $column));
        }
    }
}
