<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260814220000 extends AbstractMigration
{
    private const array AUDIT_TABLES = [
        'audit_users',
        'audit_roles',
        'audit_permissions',
        'audit_nodes',
        'audit_node_groups',
        'audit_agents',
        'audit_enrollment_tokens',
    ];

    public function getDescription(): string
    {
        return 'Add control-plane audit tables and grant audit_logs.read to Super Admin and Admin.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        foreach (self::AUDIT_TABLES as $table) {
            $this->createAuditTable($table);
        }

        $this->addSql("INSERT INTO permissions (id, code, name, description, category, created_at, updated_at) VALUES ('00000000-0000-0000-0000-000000000017', 'audit_logs.read', 'View audit logs', 'Allows viewing the audit history of Osira resources.', 'Audit', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id) VALUES ('00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000017')");
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id) VALUES ('00000000-0000-0000-0000-000000000102', '00000000-0000-0000-0000-000000000017')");
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql("DELETE FROM role_permissions WHERE permission_id = '00000000-0000-0000-0000-000000000017'");
        $this->addSql("DELETE FROM permissions WHERE id = '00000000-0000-0000-0000-000000000017'");
        foreach (array_reverse(self::AUDIT_TABLES) as $table) {
            $this->addSql('DROP TABLE '.$table);
        }
    }

    private function createAuditTable(string $table): void
    {
        $this->addSql(\sprintf('CREATE TABLE %s (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSONB DEFAULT NULL, extra_data JSONB DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))', $table));

        $hash = md5($table);
        foreach (['type', 'object_id', 'discriminator', 'transaction_hash', 'blame_id', 'created_at'] as $column) {
            $this->addSql(\sprintf('CREATE INDEX %s_%s_idx ON %s (%s)', $column, $hash, $table, $column));
        }
    }
}
